version: '4.16.2'

services:
  database:
    container_name: sitedevpro_database
    image: postgres:15.2
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=sitedevpro
      - POSTGRES_USER=sitedevpro
      - POSTGRES_DB=sitedevpro
    ports:
      - 5434:5432
