# Generated by Django 4.1.7 on 2023-03-01 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='matriculas',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
