# Generated by Django 4.1.7 on 2023-03-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_turma_matriculas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='matriculas',
        ),
    ]
